# Generated by Django 4.1.5 on 2023-01-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=2048, unique=True)),
                ('created_at', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('media_type', models.IntegerField(choices=[(0, 'Carousel Album'), (1, 'Image'), (2, 'Video')])),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.page')),
            ],
        ),
    ]
