# Generated by Django 4.1.5 on 2023-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=2048, unique=True)),
                ('page_id', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('media_type', models.IntegerField(choices=[(0, 'Carousel Album'), (1, 'Image'), (2, 'Video')])),
            ],
        ),
    ]
