# Generated by Django 4.1.5 on 2023-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ig_user_id',
            field=models.CharField(default=1, max_length=2048, unique=True),
            preserve_default=False,
        ),
    ]
